/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.xyzcorp;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Gender {
  MALE, FEMALE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"com.xyzcorp\",\"symbols\":[\"MALE\",\"FEMALE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
