/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.xyzcorp;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Shipping {
  NEXT_DAY, TWO_DAY, GROUND  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Shipping\",\"namespace\":\"com.xyzcorp\",\"symbols\":[\"NEXT_DAY\",\"TWO_DAY\",\"GROUND\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
